### ISSUE TITLE
Error import sample from VCF - Cannot load file

### ISSUE THREAD

**Issue by Jnsll** [REGOVAR/regovar-server#26]
After creating a new analysis, clicking on `Samples` in the tab menu and clinking on `Add Sample`and then on `Import new sample from VCF`, i cannot load a vcf file.
Indeed, in the `Import sample/variant data from file` window, when I click on `Browse`, i select a file in a repository and click on `Start Import!` but then the button disappears and i have a `No file selected.` next to the `Browse` button. 
What's more when I close the two windows (` Import sample/variant data from file` and  `Import sample/variant from annso database`), I can see that error window : 

<a href="http://www.casimages.com/i/170404121148463820.png.html" target="_blank" title="error_import_sample"><img src="http://nsa37.casimages.com/img/2017/04/04/170404121148463820.png" border="0" alt="error_import_sample" /></a>

When retrying, the `Start Import!` button is invisible from the beginning.
<a href="http://www.casimages.com/i/170404121047693374.png.html" target="_blank" title="error_import_sample_no_import_button"><img src="http://nsa37.casimages.com/img/2017/04/04/170404121047693374.png" border="0" alt="error_import_sample_no_import_button" /></a>

**Comment by ikit** [comment]
Can you display javascript's logs ? (F12 in your browser to display the "dev" panel, logs are in the "Console" tab)

**Comment by Jnsll** [comment]
The javascript logs : 
<a href="http://www.casimages.com/i/170405091612179879.png.html" target="_blank" title="javascript_logs_import_vcf_error"><img src="http://nsa37.casimages.com/img/2017/04/05/170405091612179879.png" border="0" alt="javascript_logs_import_vcf_error" /></a>

The `File.lastModifiedDate is deprecated. Use File.lastModified instead.` line appears when i click on the`Start import !` button.

**Comment by ikit** [comment]
Yes but it's just a warning. The error is that your browser is unable to establish the websockets connection with your server. that's why you don't see any progress in the browser. 
and it's normal, because you are trying to connect to the absolumentg.fr server which require wss connection with basic authentication. Maybe your config file is sets with bad option, otherwise, maybe you didn't install the last version of the server source. this problem of "hardcoded reference to the dev server" have been fixed few weeks ago.

**Comment by Jnsll** [comment]
My bad. Sorry for that. I thought i had cloned the lastest version with the modified option in the config file.
